### ISSUE TITLE
Two widgets on one page send the same network request even with different parameters.

### ISSUE THREAD

**Issue by SimonGoring** [throughput-ec/widget#14]
It looks like if you have two instances of the widget on a single page they both send the request as structured by the first instance.  So on the Neotoma pages I have two instances, one for sites, the other for datasets:
```html
        <b-col>
          <div>
            <h4>Site Annotations</h4>
          </div>
          <div> 
            <throughput-widget
              read-only-mode="true"
              identifier="r3d100011761" 
              :link.prop="items.siteid" 
              additional-type="site"
              orcid-client-id="APP-OKAEGWFY7MEOK4HE">
            </throughput-widget>
          </div>
        </b-col>
        <b-col>
        <div><h4>Dataset Annotations</h4></div><div>
          <throughput-widget
          read-only-mode="false"
          identifier="r3d100011761" 
          :link.prop="this.dsid" 
          additional-type="dataset"
          orcid-client-id="APP-OKAEGWFY7MEOK4HE"></throughput-widget>
        </div>
        </b-col>
```

But, when I inspect the content and the network calls, they're both calling:

```
https://throughputdb.com/api/ccdrs/annotations?dbid=r3d100011761&additionalType=site&id=2268&limit=9999
```

Which is the site call.
You can see it in action on the active landing pages: [data.neotomadb.org/2348](https://data.neotomadb.org/2348)

**Comment by sorghumking** [comment]
This is related to my adoption of [Stencil Store](https://stenciljs.com/docs/stencil-store) to maintain state in a single instance of the widget.  I hadn't considered the multiple-instances-on-one-page use case.

The state maintained by Store is global.  In your example above, the second widget instance will take on the state initialized by the first widget instance.  The Stencil devs [don't consider this a bug](https://github.com/ionic-team/stencil-store/issues/39).

We may be able to track multiple widget states in the single global Store state using a map and UUIDs, I'll give it a try.
